# Generated by Django 3.2.21 on 2024-11-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='invitation_code',
            new_name='referral_code',
        ),
    ]
