# Generated by Django 3.2.21 on 2024-11-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_invitationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationcode',
            old_name='Invitation_code',
            new_name='invitation_code',
        ),
    ]
