# Generated by Django 3.2.21 on 2024-11-24 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_invitationcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transactional_password',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_length', message='The transactional password must be exactly 4 digits.', regex='^\\d{4}$')]),
        ),
    ]
