# Generated by Django 3.2.21 on 2024-12-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_transactional_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_min_balance_for_submission_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_reg_balance_add',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Regisration Bonus Added amount'),
        ),
    ]
