# Generated by Django 3.2.21 on 2024-12-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20241201_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_submission_set_today',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='the total number of submission done set completed today'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_submission_today',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='the total number of submission done today'),
        ),
    ]
