# Generated by Django 3.2.21 on 2024-12-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20241207_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='today_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Today profit earned Earned'),
        ),
    ]
