# Generated by Django 3.2.21 on 2025-08-14 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_current_referral_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
