# Generated by Django 3.2.21 on 2025-08-14 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_session_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='session_uuid',
            new_name='session_uuid_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='session_uuid_user',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
