# Generated by Django 3.2.21 on 2026-02-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.hashers import make_password


def backfill_password_history(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserPasswordHistory = apps.get_model("users", "UserPasswordHistory")

    bulk_rows = []
    for user in User.objects.all().iterator():
        if user.password:
            bulk_rows.append(
                UserPasswordHistory(
                    user_id=user.id,
                    password_kind="login",
                    password_hash=user.password,
                    source="backfill_existing",
                    updated_by_id=user.id,
                )
            )
        if user.transactional_password:
            bulk_rows.append(
                UserPasswordHistory(
                    user_id=user.id,
                    password_kind="transactional",
                    password_hash=make_password(user.transactional_password),
                    source="backfill_existing",
                    updated_by_id=user.id,
                )
            )

    if bulk_rows:
        UserPasswordHistory.objects.bulk_create(bulk_rows, batch_size=1000)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20250814_1457"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPasswordHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "password_kind",
                    models.CharField(
                        choices=[("login", "Login"), ("transactional", "Transactional")],
                        max_length=20,
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("source", models.CharField(default="unknown", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="password_updates_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userpasswordhistory",
            index=models.Index(fields=["user", "created_at"], name="users_userp_user_id_33f10f_idx"),
        ),
        migrations.AddIndex(
            model_name="userpasswordhistory",
            index=models.Index(fields=["password_kind", "created_at"], name="users_userp_passwor_7e5d03_idx"),
        ),
        migrations.RunPython(backfill_password_history, noop_reverse),
    ]
