# Generated by Django 3.2.21 on 2024-11-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_of_sponsors', models.PositiveIntegerField(default=0, verbose_name='Percentage of Sponsors')),
                ('bonus_when_registering', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bonus When Registering (USD)')),
                ('service_availability_start_time', models.TimeField(verbose_name='Service Availability Start Time')),
                ('service_availability_end_time', models.TimeField(verbose_name='Service Availability End Time')),
                ('token_validity_period_hours', models.PositiveIntegerField(default=0, verbose_name='Token Validity Period (Hours)')),
                ('whatsapp_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp Contact')),
                ('telegram_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Contact')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username')),
                ('online_chat_url', models.URLField(blank=True, null=True, verbose_name='Online Chat URL')),
                ('erc_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='ERC Address')),
                ('trc_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='TRC Address')),
                ('minimum_balance_for_submissions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum Balance for Submissions')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Time Zone')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
