# Generated by Django 3.2.21 on 2024-11-24 07:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_settings_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
