# Generated by Django 3.2.21 on 2024-12-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='online_embed_url',
            field=models.URLField(blank=True, null=True, verbose_name='Online Embed URL'),
        ),
    ]
