# Generated by Django 3.2.21 on 2024-12-08 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_settings_online_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyResetTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reset_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Reset Time')),
                ('reset_interval_hours', models.IntegerField(default=24, verbose_name='Reset Interval in Hours')),
            ],
        ),
    ]
