# Generated by Django 3.2.21 on 2024-12-08 10:30

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_dailyresettracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyresettracker',
            name='last_reset_time',
            field=models.DateTimeField(default=administration.models.midnight_today, verbose_name='Last Reset Time'),
        ),
    ]
