# Generated by Django 3.2.21 on 2024-12-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_dailyresettracker_last_reset_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyresettracker',
            name='reset_interval_hours',
            field=models.DecimalField(decimal_places=2, default=24.0, max_digits=5, verbose_name='Reset Interval in Hours'),
        ),
    ]
