# Generated by Django 3.2.21 on 2024-11-19 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pack Name')),
                ('usd_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='The value for the USD Valuen for th pack')),
                ('daily_missions', models.PositiveIntegerField(verbose_name='Number of Daily Missions you can do')),
                ('daily_withdrawals', models.PositiveIntegerField(verbose_name='NUmber of Daily Withdrawals')),
                ('icon', models.ImageField(upload_to='pack_icons/', verbose_name='Pack Icon')),
                ('short_description', models.TextField(verbose_name='the short description for the pack')),
                ('description', models.TextField(verbose_name='the long description for the pack')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'ordering': ['usd_value'],
            },
        ),
    ]
