# Generated by Django 3.2.21 on 2024-11-29 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_auto_20241129_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='payment_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Payment Bonus'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Profit Per Mission'),
        ),
    ]
