# Generated by Django 3.2.21 on 2024-12-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_auto_20241129_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='number_of_set',
            field=models.PositiveIntegerField(default=1, verbose_name='NUmber of set for submissions'),
        ),
    ]
