# Generated by Django 3.2.21 on 2025-08-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0006_pack_number_of_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='number_of_set',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of set for submissions'),
        ),
    ]
