# Generated by Django 3.2.21 on 2025-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0007_alter_pack_number_of_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='minimum_balance_for_submissions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum Balance for Submissions (per pack)'),
        ),
    ]
