# Generated by Django 3.2.21 on 2025-08-26 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0008_pack_minimum_balance_for_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='special_product_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Special Product Profit Percentage'),
        ),
    ]
