# Generated by Django 3.2.21 on 2024-11-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['is_read', '-created_at']},
        ),
    ]
