# Generated by Django 3.2.21 on 2024-11-15 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Wallet Balance')),
                ('on_hold', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount On Hold')),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Commission Earned')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Salary Earned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
