# Generated by Django 3.2.21 on 2024-11-23 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='credit_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Credit Score'),
        ),
    ]
