# Generated by Django 3.2.21 on 2024-12-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_credit_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnHoldPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='min amount for the on hold range')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='max amount for the on hold range')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
