# Generated by Django 3.2.21 on 2024-11-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20241119_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_no',
            field=models.CharField(blank=True, editable=False, max_length=11, unique=True),
        ),
    ]
