# Generated by Django 3.2.21 on 2024-11-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_product_rating_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='product',
        ),
        migrations.AddField(
            model_name='game',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='commision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='products',
            field=models.ManyToManyField(related_name='games', to='game.Product'),
        ),
        migrations.AddField(
            model_name='game',
            name='special_product',
            field=models.BooleanField(default=False),
        ),
    ]
