# Generated by Django 3.2.21 on 2024-11-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20241119_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating_no',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
