# Generated by Django 3.2.21 on 2024-11-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_rating_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='commision',
            new_name='commission',
        ),
    ]
