# Generated by Django 3.2.21 on 2024-11-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_commision_game_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
