# Generated by Django 3.2.21 on 2024-12-02 08:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_onholdpay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0008_auto_20241123_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='NegativeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_negative_product', models.IntegerField(help_text='Number of negative products associated with the user.', validators=[django.core.validators.MinValueValidator(0)])),
                ('rank_appearance', models.IntegerField(help_text='The ranks number for the product to show.', validators=[django.core.validators.MinValueValidator(0)])),
                ('on_hold', models.ForeignKey(help_text='Reference to the on-hold payment associated with this user.', on_delete=django.db.models.deletion.CASCADE, related_name='negative_users', to='wallet.onholdpay')),
                ('user', models.OneToOneField(help_text='The user associated with negative reviews or activity.', on_delete=django.db.models.deletion.CASCADE, related_name='negative_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
