# Generated by Django 3.2.21 on 2024-12-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20241202_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating_no',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
