# Generated by Django 3.2.21 on 2025-08-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_game_rating_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Commission Percentage Used'),
        ),
    ]
