# Generated by Django 3.2.21 on 2024-12-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_paymentmethod_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Has the admin updated the status'),
        ),
    ]
