# Generated by Django 3.2.21 on 2024-12-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_withdrawal_is_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created_at']},
        ),
    ]
